### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by markseuffert** [BsNoSi/yellow-plugin-lister#1]
Hi Norbert,

 hope it's okay to open an Github issue with some feedback:

* how about using the same documentation style as the yellow-plugin-example
* please keep attribution/license if you're using plugin code from official repositories

Happy coding and greetings from Sweden, Mark 😄

**Comment by BsNoSi** [comment]
Hi Mark,

thank you for your feedback.   There is no intention or will to infringe or undermine your copyrights and license terms or to impersonate any third party work as my own. If this impression should have arisen, I must apologize expressly.

To clear this:

- I read through the documentations of the existing plugins. As far as I can see, the main differences are, that I am using questions in the headlines, I have no image and I add additional information. What are you missing / do you want to have improved?
- The code contains your full contribution (link, copyright) – I admit, that I use (typically) MIT license. I removed it to sync to your (undefined) public license. Does this match your requiries?

**Comment by markseuffert** [comment]
You can find a detailed guideline in the [example plugin for developers](https://github.com/schulle4u/yellow-plugin-example). Have a look, it shows how headlines and the content looks in most plugins. Of course you can use any style you wish in your own repository, the example plugin is just a suggestion.
  
Would be nice if you could use the [license from the official repository](https://github.com/datenstrom/yellow-plugins/blob/master/LICENSE.md). 

Thank you very much.

**Comment by BsNoSi** [comment]
All YELLOW-CMS plugins are switched to the same licence as other plugings (GNU General Public License v2.0).

**Comment by markseuffert** [comment]
Thank you, appreciate it.
