### ISSUE TITLE
Sorting?

### ISSUE THREAD

**Issue by sorenpeter** [BsNoSi/yellow-plugin-lister#3]
Hey,

How do I make Lister sort my files the other way around so it goes from Z to A (or 99 to 1) instead of A to Z (or 1 to 99)?
This way I can show my newst stuff on top by prefixing my page-files with a date.

**Comment by BsNoSi** [comment]
Hm – to be honest: Currently no idea. Too long since I created it. BUT: I am *in Yellow Update mode* which means: I put it on the list. Be so kind an let me some days to investigate (and update) this.

**Comment by BsNoSi** [comment]
Updated lister plugin.

New parameter for reverse order of list (see readme).

**Comment by sorenpeter** [comment]
Thanks, but it does not really seem to work.
It makes no difference if i do [lister - r ] or just [lister] or [lister /folder/ - no] or [lister /vj/ - r]
Do I need to add something else?

**Comment by BsNoSi** [comment]
There are FOUR parameters:

      [lister location mode style reverse]

see readme.

`[lister /folder/ - - r]`  reverses display of `/folder/`

**Comment by sorenpeter** [comment]
Ah, and you need to declare all of them. (not that clear for the readme;)
It works now with [lister - - - r]
Thank you very much!

**Comment by BsNoSi** [comment]
All plugin parameters of Yellow are recognized by position. Left out parameters are marked with `-`.
